### PR TITLE
Add `extrema`

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by mkborregaard** [comment]
We realized we needed an NaN-ignoring free version of `extrema` in Plots, and this seemed like the right place to have it.

**Comment by mkborregaard** [comment]
:tada:

**Comment by mkborregaard** [comment]
Sorry, I forgot to add `extrema` to the readme.md. Do you want another PR for that?

**Comment by mlubin** [comment]
Sure

**Pull request merged**
