### PR TITLE
SIMD mean()

### PR DESCRIPTION
**Pull request by Moelf**
as discussed in #42

### CODE REVIEW

**Comment by mlubin** [comment]
Could you show some benchmarks across different array sizes?

**Comment by Moelf** [comment]
```
julia> for n = 2:8
           v = rand([0:0.1:1;NaN], 10^n)
           @time NaNMath.mean(v)
           @time my_mean_count(v)
           println("------")
       end
  0.000001 seconds
  0.000001 seconds
------
  0.000004 seconds
  0.000003 seconds
------
  0.000040 seconds
  0.000026 seconds
------
  0.000406 seconds
  0.000256 seconds
------
  0.002085 seconds
  0.001285 seconds
------
  0.020830 seconds
  0.013247 seconds
------
  0.209454 seconds
  0.132768 seconds
------
```

**Comment by Moelf** [comment]
should a new release be tagged? NaNMath is extremely mature, I don't know how releases are usually done in this case

**Comment by mlubin** [comment]
Done: https://github.com/JuliaRegistries/General/pull/24913

**Pull request merged**
