### PR TITLE
Dispatch non Float-arrays to Base methods

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by mlubin** [comment]
This seems potentially misleading. What if someone calls ``NaNMath.sum()`` on a non-AbstractArray collection that has ``NaN`` in it? I'd rather throw a missing method error than give an unexpected answer.

**Comment by mkborregaard** [comment]
I agree with that philosophy - I'd convinced myself that only a subtype of AbstractArray{<:AbstractFloat} could possibly contain NaNs, and thus it was safe. Can you give an example? (presently 1am so off to bed)

**Comment by mlubin** [comment]
```
julia> isa((1.0,2.0,NaN),AbstractArray{<:AbstractFloat})
false

julia> sum((1.0,2.0,NaN))
NaN
```

**Comment by mkborregaard** [comment]
Hah, I didn't realize those functions worked on Tuples too. Then I agree this is too dangerous. Sorry for the bad PR! I'll deal with it downstream.
I am now officially happy with this, so a release would be great :-)

**Pull request closed without merging**
