### PR TITLE
Added docstring for sum, function sum is working with any floating point array now.

### PR DESCRIPTION
**Pull request by ufechner7**
This was tested with Julia 0.3 and Julia 0.4. On Julia 0.3 the import time increases due to the import of Docile (about one second on core i7).

### CODE REVIEW

**Comment by ufechner7** [comment]
Any idea, why the checks are failing? I don't see any error message.

**Comment by ufechner7** [comment]
From what I can see in that travis log this is not a problem on 0.3, hence not really a Docile problem. It looks like the Julia 0.4 version being used on travis is older than the fix for the
LoadError: error in method definition: function Base.sum must be explicitly imported to be extended
error that you’re seeing there. You'll need to wait until the version is updated I guess.

**Comment by mlubin** [comment]
The .travis.yml here is old. I think we'll get a more recent 0.4 if it's updated to ``language: julia``.

**Comment by ufechner7** [comment]
Is everything ok now? From my point of view it looks fine.

**Comment by mlubin** [comment]
Looks good, could you squash the commits?

**Comment by ufechner7** [comment]
I squashed them.

**Pull request merged**
